### ISSUE TITLE
where can I get version 1.1 Genome2D.swc

### ISSUE THREAD

**Issue by chaosren** [pshtif/Genome2D#39]
hi pshtif .      where can I get version 1.1 Genome2D.swc , it's disappear from bin floder

**Comment by pshtif** [comment]
There is no official build yet, so the only way to get the swc is to compile it yourself using the build_swc.hxml

**Comment by chaosren** [comment]
hi pshtif:  we wanna to know about what time final release version1.1 with right example???

carry up~
