### ISSUE TITLE
GFontTexture requests

### ISSUE THREAD

**Issue by rodrigogermanlopez** [pshtif/Genome2D#40]
Can you add the XML's size tag to GTextureFont on the next build ?
Is a useful value if we can't resize a text based on px values.

Multiple fonts in 1 atlas, is a nice feature as well to avoid breaking the batching.

**Comment by pshtif** [comment]
Definitely something I am going to add since this will be usable for our internal projects as well.

**Comment by pshtif** [comment]
Is there a software that packs multiple fonts into single atlas, if so what prefix/suffix they use, how does the format looks?

**Comment by rodrigogermanlopez** [comment]
I wish there was a software to package atlases with multiple font chars... But the basic idea is to create the font atlases that u need with the software that u already use, like Littera, shoebox, etc like:
arial_regular.png, arial_regular.fnt
arial_bold.png, arial_bold.fnt
arial_italic.png, arial_italic.fnt
and then pack the fonts pngs into another atlas.... once u have the texture in memory, u just initialize the fonts with the xml (fnt) from the original fonts' spritesheet.
That's why I told u that creating subtextures from subtextures should be supported by GTextureFont (the coordinates are not relative when u create subtextures using this approach).

So just use the fontname in the fnt file as the id... no need to "preprend" any root atlas id for this particular case.
Makes sense ?
